name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Xcode 14
        run: |
          sudo xcode-select -switch /Applications/Xcode_14.1.app
      - name: Lint
        run: swiftlint --strict # force to fix warnings too
